/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vuece_vtalk_android_jni_JabberClient */

#ifndef _Included_com_vuece_vtalk_android_jni_JabberClient
#define _Included_com_vuece_vtalk_android_jni_JabberClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vuece_vtalk_android_jni_JabberClient
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_start
  (JNIEnv *, jobject, jstring, jstring, jint);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getClientState
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_initiate
  (JNIEnv * env, jobject thiz, jobject alistener, int loggingLevel, jstring device_name, jstring app_version);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_logout
  (JNIEnv *, jobject);

JNIEXPORT jobjectArray 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getRoster
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_destroyClient
  (JNIEnv * , jobject );

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendChat
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendVCardRequest
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendVHubMessage
  (JNIEnv *, jobject, jstring, jstring, jstring);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendVHubPlayRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_addBuddy
	(JNIEnv *, jobject, jstring);

JNIEXPORT jint 		JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendPresence
	(JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jobject 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getCallRequest
  (JNIEnv *, jobject);

JNIEXPORT jboolean 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendSubscriptionResponse
  (JNIEnv *, jobject, jstring, jint);

/**
 * 	public native String sendFile(
			String fileShareId,
			String jid,
			String filePath,
			String width,
			String height,
			String previewPath
			);
 */
JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_sendFile
  (JNIEnv *, jobject,
		  jstring, //fileShareId
		  jstring, //jid
		  jstring, //filePath
		  jstring, //width
		  jstring, //height
		  jstring  //previewPath
		  );

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_cancelFileShare
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_acceptFileShare
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_declineFileShare
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_setFileShareFolder
  (JNIEnv *, jobject, jstring);
JNIEXPORT jint 	Java_com_vuece_vtalk_android_jni_JabberClient_stopStreamPlayer
	(JNIEnv *, jobject, jstring);
JNIEXPORT jint 	Java_com_vuece_vtalk_android_jni_JabberClient_resumeStreamPlayer
	(JNIEnv *, jobject, jstring);

JNIEXPORT jint 	Java_com_vuece_vtalk_android_jni_JabberClient_localMediaSeek
	(JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getCurrentMusicStreamingProgress
  (JNIEnv * , jobject );

JNIEXPORT jint JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getCurrentPlayingProgress
  (JNIEnv * , jobject );

JNIEXPORT jint JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_getNetworkPlayerState
  (JNIEnv * , jobject );

JNIEXPORT jboolean JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_isMusicStreaming
  (JNIEnv * , jobject);

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_play
(JNIEnv * , jobject , jstring , jstring);

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_pause
(JNIEnv * , jobject  );

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_resume
(JNIEnv * , jobject  );

JNIEXPORT jint 	JNICALL Java_com_vuece_vtalk_android_jni_JabberClient_seek
(JNIEnv * , jobject , jint );

//JNIEXPORT jobject 	JNICALL Java_com_vuece_vtalk_android_core_AndroidCameraRecordImpl_putImage(JNIEnv*  env,
//                jobject  thiz,jlong nativePtr,jbyteArray jbadyuvframe, jint jorientation);

#ifdef __cplusplus
}
#endif
#endif
